name: Deploy to Github Pages

on:
  repository_dispatch:
    types: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO }}
          ref: ${{ secrets.REF }}
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --baseURL="https://rmfel.github.io/"

      - name: Replace
        run: grep -rlE "(\"|\=)/(js|css|sass|img|fonts)" public/ | xargs sed -i -Ee 's/(\"|\=)(\/(js|css|sass|img|fonts))/\1https:\/\/cdn\.jsdelivr\.net\/gh\/rmfel\/rmfel\.github\.io\@pages\2/g'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
          publish_branch: pages
          full_commit_message: "update blog"
